language: node_js

node_js: 
  - "8.10"

#safelist
branches:
  only:
  - master

install:
  - npm i

jobs:
  include:
    - stage: test
    - script: npm run test

notifications:
  email:
    recipients:
      - eberdellima@gmail.com
    on_success: always
    on_failure: always

